networks:
  agent-network:
    external: true

services:
  mcp-server:
    image: mcp-server:1.0.0
    container_name: mcp-server
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - agent-network
    ports:
      - "${PORT:-8000}:8000"
    volumes:
      - ./src:/app/src
    command: ["uv", "run", "src/server.py"]
